### PR TITLE
Cosmetic fix navbar

### PR DESCRIPTION
**Pull request by silverslott**
I updated the search bar plugin, which expanded the bar in width, bumping into the "new order"- button.

### CODE REVIEW

**Review by aanil — APPROVED** [review]
👍

**Comment by ewels** [comment]
Would be better to kill the new styling if possible 😬 

I previously had CSS to wipe out all of the custom stuff that this plugin injects. Rather than dealing with the change in appearance, it would be better to revert to the previous appearance I think.. 👍🏻 

Can't remember how it looked now. Didn't I have a nice "focus and slide into view" type thing going on? Maybe that was an earlier iteration of the website..

**Comment by silverslott** [comment]
> Would be better to kill the new styling if possible 😬
> 
> I previously had CSS to wipe out all of the custom stuff that this plugin injects. Rather than dealing with the change in appearance, it would be better to revert to the previous appearance I think.. 👍🏻
> 
> Can't remember how it looked now. Didn't I have a nice "focus and slide into view" type thing going on? Maybe that was an earlier iteration of the website..

How do we do that while updating the plugin though? 🤔 

It used to be just a magnifying glass symbol with no bar. I kind of like the bar, but maybe I'm the only one 😁

**Comment by ewels** [comment]
I guess that it's all this stuff (though haven't checked):

https://github.com/NationalGenomicsInfrastructure/ngisweden.se/blob/084e1808f41072e268c3e8320f97c55fa4b3586c/wp-content/themes/ngisweden/style.css#L368-L426

This would have been overriding the previous CSS. So it's a case of updating it so that it overwrites any new CSS that the plugin update brought.

Bar / no bar is fine, but having "New order" split onto two lines doesn't look great in my opinion 😬 Also it's very "heavy", drags a lot of attention when it's not that high up the hierarchy on the web page.

image

**Pull request merged**
